### ISSUE TITLE
How does `overridesJsonFile` work?

### ISSUE THREAD

**Issue by pmpinto** [foo-software/lighthouse-check-action#100]
**Describe the bug**
I'm pointing to a local file, under `/.github/workflows`, like this:
```yml
        uses: foo-software/lighthouse-check-action@master
        with:
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          urls: 'https://…'
          overridesJsonFile: ./lighthouse-overrides.json
```

It outputs `Error: ENOENT: no such file or directory`.
Is there anything missing on the path itself? Or is this not how one refer to files in here?

**Additional context**
Alternatively, I would like to use `onlyCategories`, but there also doesn't seem to be a way to define those in the workflow file itself, or am I missing something?

Thanks!
