### ISSUE TITLE
Running on multiple urls outputs a comment with bad formatting

### ISSUE THREAD

**Issue by SeeringPhil** [foo-software/lighthouse-check-action#122]
**Describe the bug**
When running with multiple urls set, the comment that is added to the PR is not formatted properly for urls that add a subpath ('baseUrl/subPath')

Instead of filling the value in the 'URL' column, it adds a row and puts the information in the 'device' column.

<img width="757" alt="Capture d’écran, le 2023-09-06 à 12 06 05" src="https://github.com/foo-software/lighthouse-check-action/assets/9097313/cebb6b49-57ac-4bc4-8e69-2786f20583fc">

**To Reproduce**
```yml
- name: Lighthouse Check
        uses: foo-software/lighthouse-check-action@v10.0.0
        with:
          gitAuthor: ${{ github.actor }}
          gitBranch: ${{ github.ref }}
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          prCommentEnabled: true
          prCommentSaveOld: true
          device: all
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          urls: |
            ${{steps.firebase_hosting_preview.outputs.details_url}},
            ${{steps.firebase_hosting_preview.outputs.details_url}}/inventaire-neuf,
            ${{steps.firebase_hosting_preview.outputs.details_url}}/en/new-inventory
          sha: ${{ github.sha }}
```

**Expected behavior**
I would expect that the table is filled in the correct columns.

**Additional context**
N/A

Also, I think this can cause really big comments for no real gain. Maybe there could be a parameter added that would switch the formatting to a 'compactComments' that would use the tables to the fullest and output something like this?

| Device  | URL              | Accessibility | Best practices | Performance | PWA | SEO |
|---------|------------------|---------------|----------------|-------------|-----|-----|
| mobile  | baseUrl          | 95            | 90             | 95          | 80  | 100 |
| desktop | baseUrl          | 90            | 90             | 95          | 80  | 100 |
| mobile  | baseUrl/subPath1 | 92            | 90             | 95          | 80  | 100 |
| desktop | baseUrl/subPath1 | 92            | 90             | 95          | 80  | 100 |
