### ISSUE TITLE
Inaccessible "data" property

### ISSUE THREAD

**Issue by schoenwaldnils** [foo-software/lighthouse-check-action#14]
Hi there, I get following error message:

```
##[error]All URLs failed to be enqueued. Examine the "data" property of this error for details.
```

Sadly I can't find a way to access the "data" property.
The job is failing. 
The verbose option isn't getting me any more data than without it.
Can't access `lighthouseCheckResults` since the first step is failing.
Uploading artifacts isn't possible for the same reason.

My config:
```
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          apiToken: ${{ secrets.LIGHTHOUSE_TOKEN }}
          urls: 'https://18.pr.timeline.schoen.world'
          verbose: true
```

Failing action: https://github.com/schoenwaldnils/timeline/pull/18/checks?check_run_id=546516868

Any idea what could help?
