### ISSUE TITLE
S3 upload not working

### ISSUE THREAD

**Issue by iler** [foo-software/lighthouse-check-action#26]
We have tried setting up this action in our CI flow but have not got the S3 integration working. If we comment out the AWS stuff from the config .yml everything works as it should. But when we try to use the S3 integration it fails with the following error message:
```
lighthouse-check:
 AccessDenied: Access Denied
    at Request.extractError (/home/runner/work/_actions/foo-software/lighthouse-check-action/v1.0.12/node_modules/aws-sdk/lib/services/s3.js:835:35)
    at Request.callListeners (/home/runner/work/_actions/foo-software/lighthouse-check-action/v1.0.12/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/work/_actions/foo-software/lighthouse-check-action/v1.0.12/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/work/_actions/foo-software/lighthouse-check-action/v1.0.12/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/runner/work/_actions/foo-software/lighthouse-check-action/v1.0.12/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/work/_actions/foo-software/lighthouse-check-action/v1.0.12/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/runner/work/_actions/foo-software/lighthouse-check-action/v1.0.12/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/runner/work/_actions/foo-software/lighthouse-check-action/v1.0.12/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/runner/work/_actions/foo-software/lighthouse-check-action/v1.0.12/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/runner/work/_actions/foo-software/lighthouse-check-action/v1.0.12/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2020-06-01T10:50:10.084Z,
  requestId: 'id_here',
  extendedRequestId: 'id_here',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 48.0328966970021
}
```

We have tested the S3 credentials directly from terminal and have succeeded in uploading to the bucket and listing the contents of the bucket. Any pointers where we should go from here?

**Comment by adamhenson** [comment]
Hi @iler - sorry for the troubles. The error message does seem to point to the credentials. I can confirm that it's working correctly for me with [this setup](https://github.com/foo-software/lighthouse-check-action/blob/master/.github/workflows/test.yml). I would double check your configuration and how you're passing in secrets. I'm using [GitHub secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) in this repo. Can you paste your code in a comment here?

**Comment by iler** [comment]
Hi @adamhenson - no worries! Happy that you can help us :) We are using the following configuration together with GitHub secrets. We have configured the secrets in the repo where the action is setup so it should be ok. We have also double checked the credentials and also tested manually that those work. And to be sure we also gave all permissions for the user in AWS for that S3 bucket while debugging this.
```
name: Test Lighthouse Check
on:
  push:
    branches:
      - master

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.1
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@v1.0.13
        with:
          accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
          author: ${{ github.actor }}
          awsAccessKeyId: ${{ secrets.LIGHTHOUSE_CHECK_AWS_ACCESS_KEY_ID }}
          awsBucket: ${{ secrets.LIGHTHOUSE_CHECK_AWS_BUCKET }}
          awsRegion: ${{ secrets.LIGHTHOUSE_CHECK_AWS_REGION }}
          awsSecretAccessKey: ${{ secrets.LIGHTHOUSE_CHECK_AWS_SECRET_ACCESS_KEY }}
          branch: ${{ github.ref }}
          outputDirectory: /tmp/artifacts
          urls: 'list_of_urls'
          sha: ${{ github.sha }}
          slackWebhookUrl: ${{ secrets.LIGHTHOUSE_CHECK_WEBHOOK_URL }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
```
And here is a screenshot from the repository secrets https://take.ms/3YwcW.
