### ISSUE TITLE
Question - How to resolve the colors easily when manually writing comments?

### ISSUE THREAD

**Issue by Vadorequest** [foo-software/lighthouse-check-action#27]
I'm trying to integrate LH reports within my GH actions.

Our workflow is as follow:
1. We deploy on Zeit
1. We wait for the Zeit deployment to be done
1. We run LH audit

We use the `push` event, because `pull_request` has severe limitations.
Because of that, we have to comment on the PR ourselves, because [`prCommentUrl`](https://github.com/foo-software/lighthouse-check#options) option doesn't exist. 

Currently, our comment works, but colors are hardcoded (i.e: `green`) and I wonder how we could easily resolve the right color. I see [you're using JS](https://github.com/foo-software/lighthouse-check/blob/885f347ed9894462644d0fe8dea93003af447dc0/src/helpers/getLighthouseScoreColor.js) but I'm not familiar with bash and I'm not sure how to avoid code duplication.

```md
![](https://img.shields.io/badge/Accessibility-${{ fromJson(steps.lighthouseCheck.outputs.lighthouseCheckResults).data[0].scores.accessibility }}-green?style=flat-square)
```

I know this isn't so much related to `lighthouse-check-action`, but if you know of a good example/tutorial about how to run JS through github actions, it may be helpful.

Also, I think the `prCommentUrl` option would be a great addition, for people who cannot use `pull_request` trigger.

PR: https://github.com/UnlyEd/next-right-now/pull/109

```yml
      # Add a comment to the PR with lighthouse report
      - name: Comment PR (LightHouse report)
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_CI_PR_COMMENT }}
          issue-number: ${{ steps.pr_id_finder.outputs.number }}
          # Report provided by steps.lighthouseCheck.outputs.lighthouseCheckResults is a string and need to be transform into an object.
          # Then, using badges with results provided by `data[0].scores.<category>`
          # data is an array containing results of every urls tested. Thankfully, we only test one url so we don't care about the index.
          # See "fromJson" documentation: https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson
          body: |
            [GitHub Actions] - **Lighthouse report** for ${{ env.ZEIT_DEPLOYMENT_URL }}
            ![](https://img.shields.io/badge/Accessibility-${{ fromJson(steps.lighthouseCheck.outputs.lighthouseCheckResults).data[0].scores.accessibility }}-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-${{ fromJson(steps.lighthouseCheck.outputs.lighthouseCheckResults).data[0].scores.bestPractices }}-green?style=flat-square) ![](https://img.shields.io/badge/Performance-${{ fromJson(steps.lighthouseCheck.outputs.lighthouseCheckResults).data[0].scores.performance }}-orange?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-${{ fromJson(steps.lighthouseCheck.outputs.lighthouseCheckResults).data[0].scores.progressiveWebApp }}-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-${{ fromJson(steps.lighthouseCheck.outputs.lighthouseCheckResults).data[0].scores.seo }}-green?style=flat-square)

```
