### ISSUE TITLE
PR commenting not working for me (Help?)

### ISSUE THREAD

**Issue by bhatvikrant** [foo-software/lighthouse-check-action#48]
My Github workflow looks like this: 

```
name: Lighthouse Check
on:
  deployment_status:
    branches:
      - '*'
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@master
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
          outputDirectory: /tmp/artifacts
          urls: '${{ github.event.deployment_status.target_url }}'
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts

```

Here I have added `LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN` as my Github personal access token.
But for some reason, it is still not commenting the lighthouse results on any PRs.
Check [this](https://github.com/bhatvikrant/prep-station/pull/2) PR for example.

Also, can I use the `secrets.GITHUB_TOKEN` (default that github provides with every repo) instead of `secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN` ? 

PS: I have also asked this question to a wider audience on stackoverflow [here](https://stackoverflow.com/questions/67670059/pr-comments-not-working-for-lighthouse-check-action-github-action).

**Comment by adamhenson** [comment]
Hi @bhatvikrant. Sorry for the troubles and thanks for providing all those details. Our documentation isn't that great, especially on this subject. The intention of this feature was to comment on PRs, however I feel this may need to be revisited to be more robust.

My theory is that because you are not triggering this on `pull_request` this isn't working correctly (even though you have a PR open). Unless you explicitly specify `commentUrl`, then this GitHub Action will use [`context.payload.pull_request.url`](https://github.com/foo-software/lighthouse-check-action/blob/master/index.js#L27), which I'm guessing will be empty if not triggered by a `pull_request`. Your example is triggered by `deployment_status`.

To test my theory, could you make this change? Yes, we're hard-coding the PR, but this will at least isolate the issue (hopefully), and then we can brainstorm on next steps.

```diff
with:
  accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
+  commentUrl: https://api.github.com/repos/bhatvikrant/prep-station/pulls/2/reviews
  outputDirectory: /tmp/artifacts
  urls: '${{ github.event.deployment_status.target_url }}'
```

**Comment by bhatvikrant** [comment]
Thank you for replying promptly @adamhenson, I hope you are doing good! 
Sure I'll update that in the PR, please check back in 2 minutes from now.

PS: I can help you with the documentation part if you have anything in mind. 😄

**Comment by bhatvikrant** [comment]
Your theory was right, it did comment this time around

<img width="1010" alt="Screenshot 2021-05-24 at 11 19 23 PM" src="https://user-images.githubusercontent.com/50735025/119387373-7cf71680-bce6-11eb-8183-a2669f5f8795.png">

**Comment by adamhenson** [comment]
Thanks @bhatvikrant. Regarding the docs, that's something we'll have to do because it will require in-depth knowledge of this project. It's on the roadmap though... we'll get there.

Okay, well that's interesting. I think this is a clever way of populating the URLs and I'm not so sure how we can get this to work.

I wonder if you do the following - it will show up on PRs 🤔 . Want to give it a shot?

```diff
with:
  accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
-  commentUrl: https://api.github.com/repos/bhatvikrant/prep-station/pulls/2/reviews
+  commentUrl: https://api.github.com/repos/bhatvikrant/prep-station/commits/${{ github.sha }}/comments
  outputDirectory: /tmp/artifacts
  urls: '${{ github.event.deployment_status.target_url }}'
```

**Comment by bhatvikrant** [comment]
Alrighty, I ve added that.

**Comment by bhatvikrant** [comment]
Interestingly, that does seem to work!

**Comment by adamhenson** [comment]
Okay, awesome - looks like it worked @bhatvikrant 

Can you do 2 more things.

1. Remove that 1st comment with the scores, but keep the last?
2. Push up an empty commit to trigger the action again.

In theory there should only be one comment that is edited when additional commits are pushed. I want to see if this works as expected.

**Comment by bhatvikrant** [comment]
I can't delete the autogenerated 1st comment, but I have pushed an empty commit.

**Comment by adamhenson** [comment]
Great, no prob - I just want to see if the 2nd gets edited or if a new comment is created 🤞

**Comment by bhatvikrant** [comment]
Yes, I understood that, hehe :)

**Comment by bhatvikrant** [comment]
So, it created a new commit

**Comment by adamhenson** [comment]
Yep, okay looks like it will just keep creating new comments. So, this method will work, but your PR will get flooded.

If you were to do this on a PR triggered action, then only one comment would show and it would keep editing it.

I don't know if there is a better solution at this time, but I'll take some more time on it and get back to you.

**Comment by bhatvikrant** [comment]
Sure! I think I can make do with it for now, but I will be looking forward to new updates and suggestions from you! Thankyou once again for your time :) @adamhenson

**Comment by adamhenson** [comment]
No problem - and thanks for reporting this one.

**Comment by bhatvikrant** [comment]
Hey @adamhenson, so I was implementing the same as we discussed above at my work repo which is private. But for some reason I am getting this `octakit deprecated warning`, and `no commit found for SHA`.

Any idea what can be going wrong? I have implemented it exactly as we have discussed above.

<img width="1081" alt="Screenshot 2021-05-25 at 5 01 36 AM" src="https://user-images.githubusercontent.com/50735025/119418733-4b963f00-bd16-11eb-8a6a-19af6c0ca1fc.png">

**Comment by adamhenson** [comment]
Hey @bhatvikrant - I wouldn't worry about the Octokit warning. I've seen that one before an it's related to a dependency we probably need to bump.

My guess is that there is something wrong with the `commentUrl`. Make sure it reflects the repo correctly. If it's a public repo, you can send the code my way... or really just the URL for the repo and what you have for `commentUrl`.

**Comment by bhatvikrant** [comment]
Hey @adamhenson, the repo is private, but I'll share the context that should help.
So before the lighthouse-check workflow, I have this dummy-commit.yml workflow that is a workaround for deploying to Vercel for preview.

this is how `dummy-commit.yml` looks like

```yaml
name: Vercel force trigger build
on:
    push:
        branches:
            - '*'
jobs:
    trigger_vercel_build:
        runs-on: ubuntu-latest
        if: github.actor != 'mehulmpt'
        steps:
            - name: Set branch name
              id: vars
              run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

            - name: Dummy commit
              run: |
                  curl -X PUT \
                  --url https://api.github.com/repos/${{ github.repository }}/contents/.VERCEL_TRIGGER_BUILD \
                  --header 'authorization: Bearer ${{ secrets.CODEDAMN_GH_DEPLOYMENT_TOKEN }}' \
                  --header 'content-type: application/json' \
                  --data '{
                  "sha":"e69de29bb2d1d6434b8b29ae775ad8c2e48c5391",
                  "branch": "${{ steps.vars.outputs.short_ref }}",
                  "message": "trigger vercel build",
                  "content": ""
                  }'

```


and after this initiates a build for vercel preview on every commit, then the lighthouse-check workflow us run. I have a feeling this might be creating this issue. What are your thoughts?
