### ISSUE TITLE
Minimum Scores not working

### ISSUE THREAD

**Issue by Mkassabov** [foo-software/lighthouse-check-action#53]
Minimum scores don't seem to be working.
When adding the following job to my workflow:
```
- name: Handle Lighthouse Check results
  uses: foo-software/lighthouse-check-status-action@master
  with:
    lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
    minAccessibilityScore: "90"
    minBestPracticesScore: "50"
    minPerformanceScore: "50"
    minProgressiveWebAppScore: "50"
    minSeoScore: "50"
```

It returns an error: `Error: results.reduce is not a function`
