### ISSUE TITLE
mkdir: cannot create directory ‘/tmp/artifacts’: File exists

### ISSUE THREAD

**Issue by willpaige** [foo-software/lighthouse-check-action#63]
Hi,

My action keeps failing with the below: 
![Screenshot 2021-10-15 at 12 08 30 pm](https://user-images.githubusercontent.com/3032885/137478128-9b4b468e-3bdc-4ecf-8820-20833372e36f.png)

Setup:
```
lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          apiToken: ${{ secrets.FOO_ACCESS_TOKEN }}
          author: ${{ github.actor }}
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsBucket: ${{ secrets.STAGING_LIGHTHOUSE_S3_BUCKET_ARN }}
          awsRegion: ${{ secrets.AWS_ENG_TEST_REGION }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          branch: ${{ github.ref }}
          outputDirectory: /tmp/artifacts
          urls: 'https://www.website.com'
          sha: ${{ github.sha }}
          slackWebhookUrl: ${{ secrets.WORDPRESS_SLACK_URL }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
```
