### ISSUE TITLE
Avoiding credentials in urls on github comments

### ISSUE THREAD

**Issue by jbuettnerbild** [foo-software/lighthouse-check-action#74]
Hi,

i have a website with authentication and use user credentials in the url.
These credentials are posted in the github comment and i need a way to avoid this. 
Is there an option to disable the url output in the github comments?

Example Code:
```
- name: run lighthouse
    uses: foo-software/lighthouse-check-action@master
    with:
      urls: https://username:${{ secrets.USER_PASSWORD }}@private-website.com/auth&redirect=https://private-website.com
      device: 'desktop'
      outputDirectory: ${{ github.workspace }}
      commentUrl: https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.client_payload.ref }}/comments
      gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
```

![Bildschirmfoto 2021-12-15 um 09 57 01](https://user-images.githubusercontent.com/34340440/146155678-eaeb131b-ea25-4afe-97d3-ae60e3d38d47.png)
