### ISSUE TITLE
Cannot read properties of undefined (reading 'settings')

### ISSUE THREAD

**Issue by pratikaisle3** [foo-software/lighthouse-check-action#77]
**Describe the bug**
I am using  foo-software/lighthouse-check-action@master in my pipeline and  I am getting this error Cannot read properties of undefined (reading 'settings')

**To Reproduce**
So I have my workflow file in which I'm using foo-software/lighthouse-check-action@master for lighspeed test but that step is failing with below error
```
lighthouse-check:
 TypeError: Cannot read properties of undefined (reading 'settings')
    at localLighthouse (/home/runner/work/_actions/foo-software/lighthouse-check-action/master/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js:54:44)
    at getLocalLighthouseResultsWithRetries (/home/runner/work/_actions/foo-software/lighthouse-check-action/master/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js:124:35)
    at _default (/home/runner/work/_actions/foo-software/lighthouse-check-action/master/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js:***9:41)
    at /home/runner/work/_actions/foo-software/lighthouse-check-action/master/node_modules/@foo-software/lighthouse-check/dist/lighthouseCheck.js:175:67
    at new Promise (<anonymous>)
    at _default (/home/runner/work/_actions/foo-software/lighthouse-check-action/master/node_modules/@foo-software/lighthouse-check/dist/lighthouseCheck.js:69:7)
    at /home/runner/work/_actions/foo-software/lighthouse-check-action/master/dist/index.js:65:70
    at Object.<anonymous> (/home/runner/work/_actions/foo-software/lighthouse-check-action/master/dist/index.js:104:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Error: Cannot read properties of undefined (reading 'settings')
```

**Expected behavior**
Generally, it was working fine till Dec 28 2021 but you made recent changes on Dec 3 after that I am seeing this error in my pipeline please find attached files 

**Additional context**
![Screenshot_8](https://user-images.githubusercontent.com/72378060/148503864-356b511e-f7e4-4abe-a2bb-5d21322dd64c.png)
[actions.txt](https://github.com/foo-software/lighthouse-check-action/files/7827037/actions.txt)

**Comment by pratikaisle3** [comment]
I had tested this on tag 7.1.0 seems you made some changes today on 7.1.1 let me test it!

**Comment by adamhenson** [comment]
I have some major concerns here. You are running this against a fork `AISLE-3/lighthouse-check-action@7.0.0`. It looks like you even [released a version](https://github.com/AISLE-3/lighthouse-check-action/releases) of this fork and published to [the marketplace](https://github.com/marketplace/actions/aisle-lighthouse-check). **Please contact GitHub to have this removed from the marketplace immediately.**

I see many things that are wrong, just at a glance. It does not follow the documentation whatsoever.

For example, this block:

```yml
      - name: Lighthouse
        id: running-lightspeed-test
        uses: AISLE-3/lighthouse-check-action@7.0.0
        with:
          urls: 'https://idevops.tech'
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK }}
          device: 'desktop,mobile'
```

`device: 'desktop,mobile'` is not valid.

You then do this:

```
      - name: Verify Lighthouse Check results
        uses: AISLE-3/lighthouse-check-action@7.0.0
        with:
          lighthouseCheckResults: ${{ steps.running-lightspeed-test.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "75"s
          minBestPracticesScore: "75"
          minPerformanceScore: "65"
          minProgressiveWebAppScore: "90"
          minSeoScore: "50"
```

We have a separate action to handle the results, but you're using the same one `uses: AISLE-3/lighthouse-check-action@7.0.0`. As you can see in [the docs](https://www.foo.software/docs/lighthouse-check-github-action/examples#failing-workflows-by-enforcing-minimum-scores), you would use a different action `foo-software/lighthouse-check-action@master`.

I can tell that this is a problem with the configuration as it doesn't follow the documentation whatsoever. What's even more disturbing is that the fork has different code in it and you even went as far as publishing to the marketplace... and then opening an issue here for a problem with your fork.

**Please have your fork release unpublished and removed from the marketplace immediately.**

I'm closing this because `foo-software/lighthouse-check-action` is working as expected and the issue here is obviously with the fork `AISLE-3/lighthouse-check-action`.
