### ISSUE TITLE
Failing to enqueue dynamically-created URLs

### ISSUE THREAD

**Issue by TimTinkers** [foo-software/lighthouse-check-action#78]
**Describe the bug**

Hi @adamhenson thanks for the great work on this action.

I am using the excellent [Wrangler Action](https://github.com/cloudflare/wrangler-action) to automatically deploy my pull requests as previews on [Cloudflare Workers](https://workers.cloudflare.com/). As part of this, my workflow will deploy my site to a dynamic URL that I can intercept as `<branch name>.company.workers.dev`. When attempting to use my Foo API token to run Lighthouse against this site (on the branch `lighthouse`), I am experiencing the following error:
```
Run foo-software/lighthouse-check-action@master
  with:
    fooApiToken: ***
    urlsJson: [[ "***", "lighthouse.company.workers.dev" ]]
  env:
    BRANCH_NAME: lighthouse
lighthouse-check: Enqueueing Lighthouse audits.
lighthouse-check: All URLs failed to be enqueued.
lighthouse-check: Below is the API response for attempted URLs as an array. [
  { code: 'ERROR_GENERIC', message: 'Sorry, something went wrong.' },
  {
    code: 'ERROR_PAGE_MISSING',
    message: 'This page does not exist.',
    status: 422
  }
]
Error: All URLs failed to be enqueued.
```

**To Reproduce**

Set up a new free Foo account and attempt to monitor a Cloudflare Workers site being deployed via the Wrangler Action.

**Expected behavior**

I would expect the `lighthouse.company.workers.dev` site to be evaluated by Lighthouse with the results stored to Foo.

**Additional context**

This is the GitHub workflow that I am currently using.
```yaml
name: Lighthouse
on: [ pull_request ]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Prepare environment
        run: |
          echo "BRANCH_NAME=$(echo "${{ github.head_ref || github.ref }}" | sed s'/refs\/heads\///g' | sed s'/[/.]/-/g' | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}
      - name: Install dependencies
        run: npm install
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          fooApiToken: ${{ secrets.FOO_API_SECRET }}
          urlsJson: '[[ "${{ secrets.FOO_API_SECRET }}", "${{ env.BRANCH_NAME }}.company.workers.dev" ]]'

```
Thank you!

**Comment by adamhenson** [comment]
Hi @TimTinkers - thank you for providing the details! You're on the right track and sorry that parts of the documentation isn't clear. I will improve this part of the config section and also I noticed a broken link in the docs... so, I'm sure that didn't help.

I see 2 things, but the error is coming from the first.

1. You'll actually need 2 different types of tokens here... the API token, which appears to have correctly configured by you, but also the **page token**. I think this part needs to be improved in the docs.

So, this line should have the page token. In the example below, I named the secret `FOO_PAGE_TOKEN_SECRET`, but that can obviously be anything... or hard-coded.

```
- urlsJson: '[[ "${{ secrets.FOO_API_SECRET }}", "${{ env.BRANCH_NAME }}.company.workers.dev" ]]'
+ urlsJson: '[[ "${{ secrets.FOO_PAGE_TOKEN_SECRET }}", "${{ env.BRANCH_NAME }}.company.workers.dev" ]]'
```

You're probably wondering where the heck you get that, and again - I think it's missing from the docs. You can get it from the [page dashboard on Foo](https://www.foo.software/dashboard/pages). Example below from the demo account.

![Demo-dashboard-showing-real-data-to-evaluate-page-experience-Foo](https://user-images.githubusercontent.com/747743/149162467-15d1c3fc-4a56-4747-b2de-212587ab86a0.png)

2. Once you have corrected the above, I would imagine another error to be thrown... and I think the fix is simple here. `lighthouse.company.workers.dev` isn't a fully qualified URL, so I think the fix is to just prefix it with `http://` or `https://`

Let me know if this works for you and / or close the issue if it does. Otherwise feel free to comment with further issues or questions regarding this.

**Comment by TimTinkers** [comment]
@adamhenson thanks for the reply and for catching that URL issue for me! That all makes sense.

Regarding the page token... how can I get that without adding it to the dashboard? I envision this being part of our CI where these pages are being created dynamically for every branch. I don't know their names ahead of time. All I know is that they are a subdomain of `.company.workers.dev`.

Can I get a single fixed Page API token with wildcard support? i.e. would the token for `https://*.company.workers.dev` be valid to use here?

It's very similar to the Vercel example from the docs:
```yaml
name: Lighthouse
on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./sub-directory
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          fooApiToken: ${{ secrets.LIGHTHOUSE_CHECK_API_TOKEN }}
          urlsJson: '[["fooPageToken", "${{ steps.now.outputs.preview-url }}"]]'
```
Except here I'm confused because it sounds like the Vercel example also wouldn't even work because `fooPageToken` would be completely dynamic and different depending on the value of `steps.now.outputs.preview-url`, no?
