### ISSUE TITLE
ERR_LAUNCHER_PATH_NOT_SET error

### ISSUE THREAD

**Issue by uluzox** [foo-software/lighthouse-check-action#79]
Hi, 
I am trying to use this GH Action on a GitHub Enterprise instance.

My workflow
```
---
name: Lighthouse

on:
  workflow_dispatch

jobs:
  lighthouse:
    runs-on: [self-hosted]
    steps:
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@v7.1.1
        with:
          urls: 'https://google.de'
```

On run it fails with

```
lighthouse-check: Auditing mobile (1/1): https://google.de
lighthouse-check:
 ChromePathNotSetError
    at new LauncherError (/runner/_work/_actions/foo-software/lighthouse-check-action/v7.1.1/node_modules/chrome-launcher/dist/utils.js:26:22)
    at new ChromePathNotSetError (/runner/_work/_actions/foo-software/lighthouse-check-action/v7.1.1/node_modules/chrome-launcher/dist/utils.js:33:9)
    at Object.linux (/runner/_work/_actions/foo-software/lighthouse-check-action/v7.1.1/node_modules/chrome-launcher/dist/chrome-finder.js:128:15)
    at Function.getFirstInstallation (/runner/_work/_actions/foo-software/lighthouse-check-action/v7.1.1/node_modules/chrome-launcher/dist/chrome-launcher.js:117:51)
    at Launcher.launch (/runner/_work/_actions/foo-software/lighthouse-check-action/v7.1.1/node_modules/chrome-launcher/dist/chrome-launcher.js:176:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.launch (/runner/_work/_actions/foo-software/lighthouse-check-action/v7.1.1/node_modules/chrome-launcher/dist/chrome-launcher.js:37:5)
    at async exports.default (/runner/_work/_actions/foo-software/lighthouse-check-action/v7.1.1/node_modules/@foo-software/lighthouse-persist/dist/lighthousePersist.js:93:26)
    at async localLighthouse (/runner/_work/_actions/foo-software/lighthouse-check-action/v7.1.1/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js:83:7)
    at async getLocalLighthouseResultsWithRetries (/runner/_work/_actions/foo-software/lighthouse-check-action/v7.1.1/node_modules/@foo-software/lighthouse-check/dist/localLighthouse.js:124:29) {
  message: 'The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.',
  code: 'ERR_LAUNCHER_PATH_NOT_SET'
}
Error: The CHROME_PATH environment variable must be set to a Chrome/Chromium executable no older than Chrome stable.
```
