### ISSUE TITLE
Report output reads "Lighthouse report requires JavaScript. Please enable."

### ISSUE THREAD

**Issue by arenoir** [foo-software/lighthouse-check-action#88]
When running this action with the `outputDirectory` all outputted html reports read "Lighthouse report requires JavaScript. Please enable."  The results.json file is intact and the rest of the action works as intended. 

Has the `ubuntu-latest` image changed?

Here is the relevant configuration:

```
on:
  release:
    types: [published]
  push:
    branches:
      - main
jobs:
  apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - 
        name: Create artifacts directory
        run: mkdir -p ${{ github.workspace }}/tmp/artifacts
      -
        name: Lighthouse
        id: lighthouse
        uses: foo-software/lighthouse-check-action@v8.0.0
        with:
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          device: all
          urls: >-
            ${{ fromJSON(steps.tf_output.outputs.stdout).service_url.value }}/en-us,
            ${{ fromJSON(steps.tf_output.outputs.stdout).service_url.value }}/en-gb
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Lighthouse reports
          path: ${{ github.workspace }}/tmp/artifacts
      - 
        name: Verify Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@v1.0.1
        with:
          lighthouseCheckResults: ${{ steps.lighthouse.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "80"
          minBestPracticesScore: "80"
          minPerformanceScore: "40"
          minSeoScore: "80"
```

![Screen Shot 2022-03-29 at 11 49 53 AM](https://user-images.githubusercontent.com/113590/160683788-b8dd4155-c114-49cd-b007-96c2c90a9577.png)
